import type { SkillGroup, SkillItem } from '@/shared/types/content'

/**
 * Tech stack content for Berhe.
 * Main stack = primary production toolkit.
 */

export const mainStack: SkillItem[] = [
  {
    id: 'typescript',
    name: 'TypeScript',
    tooltip: 'Typed JavaScript for production apps',
    icon: 'typescript',
    color: '#3178C6',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    tooltip: 'React framework for production web apps',
    icon: 'nextjs',
    color: '#FFFFFF',
  },
  {
    id: 'react',
    name: 'React',
    tooltip: 'Component-driven user interfaces',
    icon: 'react',
    color: '#61DAFB',
  },
  {
    id: 'nestjs',
    name: 'NestJS',
    tooltip: 'Modular TypeScript backend framework',
    icon: 'nestjs',
    color: '#E0234E',
  },
  {
    id: 'docker',
    name: 'Docker',
    tooltip: 'Containerized development and deployment',
    icon: 'docker',
    color: '#2496ED',
  },
]

export const fullStackGroups: SkillGroup[] = [
  {
    id: 'languages',
    title: 'Languages',
    skills: [
      {
        id: 'typescript',
        name: 'TypeScript',
        tooltip: 'Typed JavaScript for production apps',
        icon: 'typescript',
        color: '#3178C6',
      },
      {
        id: 'javascript',
        name: 'JavaScript',
        tooltip: 'Core language across frontend and backend',
        icon: 'javascript',
        color: '#F7DF1E',
      },
      {
        id: 'html5',
        name: 'HTML5',
        tooltip: 'Semantic markup for web applications',
        icon: 'html5',
        color: '#E34F26',
      },
      {
        id: 'css3',
        name: 'CSS3',
        tooltip: 'Layout, styling, and responsive UI',
        icon: 'css3',
        color: '#1572B6',
      },
    ],
  },
  {
    id: 'frontend',
    title: 'Frontend',
    skills: [
      {
        id: 'nextjs',
        name: 'Next.js',
        tooltip: 'React framework for production web apps',
        icon: 'nextjs',
        color: '#FFFFFF',
      },
      {
        id: 'react',
        name: 'React',
        tooltip: 'Component-driven user interfaces',
        icon: 'react',
        color: '#61DAFB',
      },
      {
        id: 'tanstackquery',
        name: 'TanStack Query',
        tooltip: 'Async server state and data fetching',
        icon: 'tanstackquery',
        color: '#FF4154',
      },
      {
        id: 'zustand',
        name: 'Zustand',
        tooltip: 'Lightweight client state management',
        icon: 'zustand',
        color: '#FFFFFF',
      },
      {
        id: 'redux',
        name: 'Redux',
        tooltip: 'Predictable global state management',
        icon: 'redux',
        color: '#764ABC',
      },
      {
        id: 'zod',
        name: 'Zod',
        tooltip: 'TypeScript-first schema validation',
        icon: 'zod',
        color: '#3E67B1',
      },
      {
        id: 'i18n',
        name: 'i18n',
        tooltip: 'Internationalization for multi-language UIs',
        icon: 'i18n',
        color: '#26A69A',
      },
      {
        id: 'tailwind',
        name: 'Tailwind CSS',
        tooltip: 'Utility-first styling for product UIs',
        icon: 'tailwind',
        color: '#06B6D4',
      },
    ],
  },
  {
    id: 'backend',
    title: 'Backend',
    skills: [
      {
        id: 'nestjs',
        name: 'NestJS',
        tooltip: 'Modular TypeScript backend framework',
        icon: 'nestjs',
        color: '#E0234E',
      },
      {
        id: 'nodejs',
        name: 'Node.js',
        tooltip: 'Server runtime for APIs and services',
        icon: 'nodejs',
        color: '#339933',
      },
      {
        id: 'express',
        name: 'Express.js',
        tooltip: 'HTTP APIs for e-commerce and business apps',
        icon: 'express',
        color: '#FFFFFF',
      },
      {
        id: 'jwt',
        name: 'JWT',
        tooltip: 'Token-based authentication for APIs',
        icon: 'jwt',
        color: '#FFFFFF',
      },
    ],
  },
  {
    id: 'databases',
    title: 'Databases',
    skills: [
      {
        id: 'prisma',
        name: 'Prisma',
        tooltip: 'Type-safe ORM used in full stack products',
        icon: 'prisma',
        color: '#FFFFFF',
      },
      {
        id: 'postgresql',
        name: 'PostgreSQL',
        tooltip: 'Relational database for production systems',
        icon: 'postgresql',
        color: '#4169E1',
      },
      {
        id: 'redis',
        name: 'Redis',
        tooltip: 'Caching and fast in-memory data store',
        icon: 'redis',
        color: '#DC382D',
      },
      {
        id: 'mysql',
        name: 'MySQL',
        tooltip: 'Relational storage for business applications',
        icon: 'mysql',
        color: '#4479A1',
      },
    ],
  },
  {
    id: 'devops',
    title: 'DevOps & Infrastructure',
    skills: [
      {
        id: 'docker',
        name: 'Docker',
        tooltip: 'Containerized development and deployment',
        icon: 'docker',
        color: '#2496ED',
      },
      {
        id: 'githubactions',
        name: 'GitHub Actions',
        tooltip: 'CI/CD pipelines and automation',
        icon: 'githubactions',
        color: '#2088FF',
      },
      {
        id: 'nginx',
        name: 'Nginx',
        tooltip: 'Reverse proxy and web server',
        icon: 'nginx',
        color: '#009639',
      },
      {
        id: 'git',
        name: 'Git',
        tooltip: 'Version control across all projects',
        icon: 'git',
        color: '#F05032',
      },
    ],
  },
  {
    id: 'other',
    title: 'Others',
    skills: [
      {
        id: 'jest',
        name: 'Jest',
        tooltip: 'Unit and integration testing',
        icon: 'jest',
        color: '#C21325',
      },
      {
        id: 'sentry',
        name: 'Sentry',
        tooltip: 'Error monitoring and production observability',
        icon: 'sentry',
        color: '#362D59',
      },
      {
        id: 'websockets',
        name: 'WebSockets',
        tooltip: 'Realtime client-server communication',
        icon: 'websockets',
        color: '#FFFFFF',
      },
      {
        id: 'jira',
        name: 'Jira',
        tooltip: 'Project tracking and agile delivery',
        icon: 'jira',
        color: '#0052CC',
      },
    ],
  },
]

/** Flat unique list for the All skills icon grid */
export const allSkills: SkillItem[] = [
  {
    id: 'typescript',
    name: 'TypeScript',
    tooltip: 'Typed JavaScript for production apps',
    icon: 'typescript',
    color: '#3178C6',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    tooltip: 'Core language across frontend and backend',
    icon: 'javascript',
    color: '#F7DF1E',
  },
  {
    id: 'html5',
    name: 'HTML5',
    tooltip: 'Semantic markup for web applications',
    icon: 'html5',
    color: '#E34F26',
  },
  {
    id: 'css3',
    name: 'CSS3',
    tooltip: 'Layout, styling, and responsive UI',
    icon: 'css3',
    color: '#1572B6',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    tooltip: 'React framework for production web apps',
    icon: 'nextjs',
    color: '#FFFFFF',
  },
  {
    id: 'react',
    name: 'React',
    tooltip: 'Component-driven user interfaces',
    icon: 'react',
    color: '#61DAFB',
  },
  {
    id: 'tanstackquery',
    name: 'TanStack Query',
    tooltip: 'Async server state and data fetching',
    icon: 'tanstackquery',
    color: '#FF4154',
  },
  {
    id: 'zustand',
    name: 'Zustand',
    tooltip: 'Lightweight client state management',
    icon: 'zustand',
    color: '#FFFFFF',
  },
  {
    id: 'redux',
    name: 'Redux',
    tooltip: 'Predictable global state management',
    icon: 'redux',
    color: '#764ABC',
  },
  {
    id: 'zod',
    name: 'Zod',
    tooltip: 'TypeScript-first schema validation',
    icon: 'zod',
    color: '#3E67B1',
  },
  {
    id: 'i18n',
    name: 'i18n',
    tooltip: 'Internationalization for multi-language UIs',
    icon: 'i18n',
    color: '#26A69A',
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    tooltip: 'Utility-first styling for product UIs',
    icon: 'tailwind',
    color: '#06B6D4',
  },
  {
    id: 'nestjs',
    name: 'NestJS',
    tooltip: 'Modular TypeScript backend framework',
    icon: 'nestjs',
    color: '#E0234E',
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    tooltip: 'Server runtime for APIs and services',
    icon: 'nodejs',
    color: '#339933',
  },
  {
    id: 'express',
    name: 'Express.js',
    tooltip: 'HTTP APIs for e-commerce and business apps',
    icon: 'express',
    color: '#FFFFFF',
  },
  {
    id: 'jwt',
    name: 'JWT',
    tooltip: 'Token-based authentication for APIs',
    icon: 'jwt',
    color: '#FFFFFF',
  },
  {
    id: 'prisma',
    name: 'Prisma',
    tooltip: 'Type-safe ORM used in full stack products',
    icon: 'prisma',
    color: '#FFFFFF',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    tooltip: 'Relational database for production systems',
    icon: 'postgresql',
    color: '#4169E1',
  },
  {
    id: 'redis',
    name: 'Redis',
    tooltip: 'Caching and fast in-memory data store',
    icon: 'redis',
    color: '#DC382D',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    tooltip: 'Relational storage for business applications',
    icon: 'mysql',
    color: '#4479A1',
  },
  {
    id: 'docker',
    name: 'Docker',
    tooltip: 'Containerized development and deployment',
    icon: 'docker',
    color: '#2496ED',
  },
  {
    id: 'githubactions',
    name: 'GitHub Actions',
    tooltip: 'CI/CD pipelines and automation',
    icon: 'githubactions',
    color: '#2088FF',
  },
  {
    id: 'nginx',
    name: 'Nginx',
    tooltip: 'Reverse proxy and web server',
    icon: 'nginx',
    color: '#009639',
  },
  {
    id: 'git',
    name: 'Git',
    tooltip: 'Version control across all projects',
    icon: 'git',
    color: '#F05032',
  },
  {
    id: 'jest',
    name: 'Jest',
    tooltip: 'Unit and integration testing',
    icon: 'jest',
    color: '#C21325',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    tooltip: 'Error monitoring and production observability',
    icon: 'sentry',
    color: '#362D59',
  },
  {
    id: 'websockets',
    name: 'WebSockets',
    tooltip: 'Realtime client-server communication',
    icon: 'websockets',
    color: '#FFFFFF',
  },
  {
    id: 'jira',
    name: 'Jira',
    tooltip: 'Project tracking and agile delivery',
    icon: 'jira',
    color: '#0052CC',
  },
]

/** @deprecated Prefer mainStack / fullStackGroups / allSkills */
export const skillGroups: SkillGroup[] = fullStackGroups
